### PR TITLE
Adds support for Xcode8 Beta4 / Swift 2.3

### PR DESCRIPTION
**Pull request by alliannas**
## Description
Updates project settings for Xcode8 Beta 4
Adds support for Swift 2.3

This is to help with upgrading projects that are using this library in Xcode 8 with Swift 2.3.

## Checklist

- [x] Documentation has been added or updated.
- [x] All applicable classes have unit tests.
- [x] This PR contains no commented out code.

### CODE REVIEW

**Comment by johannth** [comment]
LGTM. @alliannas what is the plan with this? Merging and releasing or keeping on a branch until Xcode 8 gets released?

**Comment by alliannas** [comment]
Going to try this in Xcode 7 and if all goes well it would be best to merge it.

**Comment by alliannas** [comment]
No warnings in either IDE and all tests pass. I think its safe to merge.

**Comment by johannth** [comment]
LGTM

**Pull request merged**
